### ISSUE TITLE
Installation of CUDA version

### ISSUE THREAD

**Issue by oskaradermecker** [Manza12/nnMorpho#9]
Hi! Thanks for the hard work on the package. I am trying to install nnMorpho, but can't quite get the CUDA part to work. More specifically, when I try to run the tests, I get a `No module named 'morphology_cuda'` error. I have tried to run the install.sh file in the CUDA folder with and without the prefix. Can you clarify what you mean by:

> If you use Unix, you may need to edit the script to select your installation folder for Python in the --prefix parameter for the setup.py install.

I am using Python 3.7.10 and Debian 10. Thanks!

**Comment by Manza12** [comment]
Hi!
I'm very glad you found useful nnMorpho. 
First, I want to apologize for the strange two-steps installation process; I actually followed a tutorial on how to build C++/CUDA extensions on PyTorch and I wanted to separate this part from the pure python code (which is actually simply the interface for calling C++/CUDA functions)
Regarding your issue, the install.sh script is only a shortcut for `python3 setup.py install` with the `--prefix` option. I did that because it was the way to making it work in my Ubuntu 20.04.
I checked out the documentation https://docs.python.org/3/install/ and found that maybe it is better to choose the `--user` option.
If this doesn't work, try to change the the value in the `--prefix` option to your actual prefix, that can be checked using `sys.prefix` in a Python console.
Just in case, I confirm that your error says that you don't have the module morphology_cuda installed, which is the complied version of the C++/CUDA code adapted to your machine. By the way, you will need CUDA compilation tools for compiling this.
I hope I will make the process easier for later releases.
Keep comenting on this issue if you need more help.

**Comment by oskaradermecker** [comment]
Thanks so much for the solution Manza! I managed to make it work with your suggestions. 

Again, thanks for the hard work and the help -- this will be very useful!
